---
name: XML-Grammar-Fortune
version: 0.0108
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
abstract: convert the FortunesXML grammar to other formats and from plaintext.
license: mit
resources:
  license: http://www.opensource.org/licenses/mit-license.php
requires:
  Class::Accessor: 0
  File::Spec: 0
  Text::Format: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  perl: 5.008
  vars: 0
  warnings: 0
build_requires:
  IO::String: 0
  Test::Differences: 0
  Test::More: 0
provides:
  XML::Grammar::Fortune:
    file: lib/XML/Grammar/Fortune.pm
    version: 0.0108
  XML::Grammar::Fortune::ToText:
    file: lib/XML/Grammar/Fortune/ToText.pm
    version: 0.0108
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
